---
title: "Exploratory Data Analysis for Titanic Data"
author: "Yue Pan"
---

### About
This data set provides passengers' information in the Titanic Disaster, summarized according to economic status (class), sex, age and survival etc. 
There are 891 observations in this dataset, with 12 variables in total. 


### Exploratory Data Analysis
```{r}
setwd('/Applications/MAMP/htdocs/titanic/data')
df <- read.csv('titanic_data.csv')
```

```{r}
dim(df)
str(df)
summary(df)
```

```{r}
head(df)
```

```{r}
titanicTab <- xtabs(~Survived + Pclass + Sex, df)
ftable(titanicTab) 
```

```{r}
counts <- table(df$Sex, df$Pclass)
barplot(counts, main="Passenger Distribution by Sex and Pclass",
  xlab="Pclass", col=c("darkblue","red"),
 	legend = rownames(counts), beside=FALSE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
df_survived = subset(df, Survived== 1)
counts <- table(df_survived$Sex, df_survived$Pclass)
barplot(counts, main="Survived Passenger Distribution by Sex and Pclass",
  xlab="Pclass", col=c("darkblue","red"),
 	legend = rownames(counts), beside=FALSE)
```

Distribution of Age and Fare: 

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(gridExtra)
plot1 <- qplot(df$Age, xlab="Passenger Age (in years)")
plot2 <- qplot(df$Fare, xlab="Passenger Fare (in pounds)")
grid.arrange(plot1, plot2, ncol=2)
```